---
name: build base container

on:
  push:
    branches:
      - devel
    paths:
    - .github/workflows/container_build_template.yml
    - avd-containers/base/**
  workflow_dispatch:
    branches:
      - devel

jobs:

  build_base:

    uses: ./.github/workflows/container_build_template.yml

    strategy:
      matrix:
        container_name: [base]
        python_version: ["3.9", "3.10", "3.11"]
        include:
          - python_version: "3.11"
            container_tags: latest

    with:
      container_name: ${{ matrix.container_name }}
      python_version: ${{ matrix.python_version }}
      container_tags: ${{ matrix.container_tags }}
